version: "3"

services:
  question_service:
    container_name: berwise_question_service
    build:
      context: .
      dockerfile: ./services/question_service/Dockerfile
    env_file:
      - .env
    command: ["./data/wait-for-it.sh", "db:5432", "--", "gunicorn", "services.question_service.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:${WEB_PORT}"]
    restart: unless-stopped
    ports:
      - "23000:${WEB_PORT}"
    depends_on:
      - db
    volumes:
      - ./logs/:/logs

  audio_service:
    container_name: berwise_audio_service
    build:
      context: .
      dockerfile: ./services/audio_service/Dockerfile
    env_file:
      - .env
    command: ["./data/wait-for-it.sh", "db:5432", "--", "gunicorn", "services.audio_service.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:${WEB_PORT}"]
    restart: unless-stopped
    ports:
      - "23001:${WEB_PORT}"
    depends_on:
      - db
    volumes:
      - ./logs/:/logs

  db:
    container_name: berwise_db
    image: postgres:latest
    restart: always
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  postgres:
